### ISSUE TITLE
Commands do not work

### ISSUE THREAD

**Issue by tgduke** [rainfordays/AutoOpen#1]
/ao
/ao blacklist item
/autoopen
/autoopen blacklist item

Nothing works.
Also, it tries to open the locked item Ironbound locked chest

**Comment by rainfordays** [comment]
its because the command is "bl", i added blacklist as a command as well and also added any item with "lock" to not be opened. Fixed in 1.5.1

**Comment by tgduke** [comment]
It is not the case. I’ve just tried. /bl does nothing. The chest says “locked” and not “lock”. So it is still trying to open ironbound locked chest

**Comment by rainfordays** [comment]
Christ... 

Ill write it out explicit. 
The command is /ao bl [itemlink]

I know the name is ’Locked’ but by looking for the word ’Lock’ I dont have to also check for Lockbox, since they both contain the word ’Lock’.

**Comment by tgduke** [comment]
Christ...

Try running /ao bl [itemlink] - you can't click enter.
Also, try get an Ironbound locked chest - it keeps trying to open it. 

I'm not making shit up here.
